### ISSUE TITLE
I am not able to install the requirements. Please help !

### ISSUE THREAD

**Issue by Shubhamverma2796** [RiajulKashem/SRMS#10]
![Screenshot (458)](https://user-images.githubusercontent.com/54266411/94817147-582df600-041a-11eb-813b-534d70fa5f45.png)

**Comment by vishnusreddy** [comment]
Are you running the `pip install -r requirements.txt` in the virtual environment?

**Comment by Shubhamverma2796** [comment]
> Are you running the `pip install -r requirements.txt` in the virtual environment?

Yes

**Comment by vishnusreddy** [comment]
You can check out the PR I made. I have corrected the README.md. Use that and it works. I tested it. Though the username and password are still unclear. That can be fixed by creating a superuser. The command for it is `python manage.py createsuperuser`.

**Comment by vishnusreddy** [comment]
> > Are you running the `pip install -r requirements.txt` in the virtual environment?
> 
> Yes

I always have a hard time using virtual environments on powershell with VS code. Check if your venv is active.

**Comment by Shubhamverma2796** [comment]
> > > Are you running the `pip install -r requirements.txt` in the virtual environment?
> > 
> > 
> > Yes
> 
> I always have a hard time using virtual environments on powershell with VS code. Check if your venv is active.

I am sure that my virtual env is active

**Comment by vishnusreddy** [comment]
The OG maintainer has 2 files, one requirments.txt and one requirements.txt. Keep that in mind as well.

**Comment by vishnusreddy** [comment]
> I am sure that my virtual env is active

Are you using makevirtualenv or virtalenv?

**Comment by vishnusreddy** [comment]
> The OG maintainer has 2 files, one requirments.txt and one requirements.txt. Keep that in mind as well.

What I did was initially install the requirements.txt and then requirments.txt. This worked for me.

**Comment by vishnusreddy** [comment]
If it worked please close the issue.

**Comment by vishnusreddy** [comment]
If it still does not work, it is definitely an issue with the virtual environment. I created a sandbox and tried it out without creating a venv and I got the same error as you did.

**Comment by Shubhamverma2796** [comment]
Here is what I did 
1.  virtualenv env
2. cd env
3. ./Scripts/activate
4. cd ..
5.  pip install -r requirements.txt

Please guide me if I am doing something wrong

**Comment by Shubhamverma2796** [comment]
I tried pip install -r requirments.txt then installed psycopg2, and then it worked successfully. Thanks for the help. I am closing this issue.

**Comment by vishnusreddy** [comment]
Thank you.
