### ISSUE TITLE
not able to start server

### ISSUE THREAD

**Issue by noob0701** [RiajulKashem/SRMS#2]
Is the server running on host "localhost" (::1) and accepting                    TCP/IP connections on port 5432?                                         could not connect to server: Connection refused (0x0000274D/10061)                       Is the server running on host "localhost" (127.0.0.1) and accepting              TCP/IP connections on port 5432?
--

**Comment by andressasantiago** [comment]
I have the same problem!

**Comment by riajulkashem** [comment]
Follow this: https://github.com/RiajulKashem/SRMS/issues/3
