### ISSUE TITLE
Not able to start the server

### ISSUE THREAD

**Issue by andressasantiago** [RiajulKashem/SRMS#3]
Is the server running on host "localhost" (::1) and accepting TCP/IP connections on port 5432? could not connect to server: Connection refused (0x0000274D/10061) Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432?

**Comment by ghost** [comment]
I met this issuse either

**Comment by anhuihu** [comment]
missing sqlliet.sql file ?

**Comment by riajulkashem** [comment]
@andressasantiago what you're using PostgreSQL DB? @anhuihu  Change Database Settings
`DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}`
then run `python manage.py makemigrations` and `python manage.py migrate`
Hope you got it :)

**Comment by manish-rajpurohitt** [comment]
Or Activate Environment and runserver.

**Comment by anhuihu** [comment]
yeah，i got it，thks
